caracal-pipeline/cult-cargo

cultcargo/tricolour.yml

Access tricolour's config file from parent when linked

minor param update

---

cultcargo/builder/cargo-manifest.yml
cultcargo/genesis/cult-cargo-base.yml
cultcargo/images/python-astro/Dockerfile
cultcargo/images/rfinder/Dockerfile
cultcargo/rfinder.yml
pyproject.toml

Simple Flag Statistics Run:
And for more: `summary_options: [scan,corr,ant,freq]`
```
rfinder-summary-stats-0:
info: report initial flagging statistics from rfinder
cab: rfinder
params:
ms: =recipe.ms
output_dir: "{recipe.dir-out-base}/"
label: test
ncpu: =recipe.ncpu
```
```
.0# 2024-02-13 12:30:42,029; ------ Reading default parameter file in your directory ------
.0#
.0# 2024-02-13 12:30:42,068; ------ Updating arguments given from terminal ------
.0#
.0# 2024-02-13 12:30:42,478; ------ STARTING RFI analysis ------
.0#
.0# 2024-02-13 12:30:42,478;     ... Field, Antenna & Bandwidth Info ...
.0#
.0# 2024-02-13 12:30:42,626;    Field with name T16R02C02 (Field ID = 0)
.0# 2024-02-13 12:30:42,716;    Total number of antennas:       61
.0# 2024-02-13 12:30:42,716;    Antenna names: …
```

Add rfinder

---

cultcargo/builder/build-cargo.py
cultcargo/builder/cargo-manifest.yml
cultcargo/genesis/cult-cargo-base.yml
cultcargo/genesis/wsclean/__init__.py
cultcargo/genesis/wsclean/wsclean-base.yml
cultcargo/images/Dockerfile.generic.pip
cultcargo/images/casa/Dockerfile
cultcargo/images/casa/Dockerfile.base
cultcargo/images/casa6/Dockerfile
cultcargo/images/python-astro/Dockerfile
cultcargo/images/rfinder/Dockerfile
cultcargo/images/tricolour/Dockerfile
cultcargo/images/wsclean/Dockerfile.build
cultcargo/images/wsclean/Dockerfile.build.2x
pyproject.toml

See #10 and #12.
NB: change version in pyproject.toml to 0.1.2 before merging.

Updated build script, and fixed #12

---

.github/workflows/python-package.yml
cultcargo/builder/build-cargo.py
cultcargo/images/python-astro/Dockerfile
pyproject.toml

List images

---

.github/workflows/python-package.yml
cultcargo/builder/build_cargo.py
pyproject.toml

Builder bin

---

cultcargo/genesis/quartical/argument_schema.yaml

Make QuartiCal gain and log directory parameters URI and Directory respectively.

---

.github/workflows/python-package.yml
cultcargo/taql.yml
pyproject.toml

@JSKenyon could you please break taql.update again, and see if it errors out properly now?

added error wrangler for taql.update

---

cultcargo/genesis/wsclean/wsclean-base.yml

Tiny PR - does what it says on the label.

Add missing reorder option.

---

cultcargo/genesis/wsclean/__init__.py

See also https://github.com/caracal-pipeline/stimela/pull/326

fixed must_exist settings of various wsclean outputs

---

cultcargo/casa-flag.yml

```
mode:
info: Flagging mode
choices:
- manual
- clip
- quack
- shadow
- elevation
- tfcrop
- rflag
- extend
- unflag
```

Add casa-flagdata cab

---

cultcargo/images/casa6/Dockerfile
cultcargo/images/casa6/casasiteconfig.py

Ooops, forgot to commit before release. I'll rebuild the casa6 images with these fixes in place.

final fixes for CASA images

---

cultcargo/casa/clearcal.yml
cultcargo/casa/mstransform.yml
cultcargo/casa/plotants.yml

Add mstransform, clearcal and plotants to casa cabs

Add more casa cabs

---

cultcargo/casa/flag.yml
cultcargo/genesis/quartical/argument_schema.yaml
cultcargo/genesis/wsclean/__init__.py
pyproject.toml

@JSKenyon please review, and check minor change that affects QC.

updated to stimela 2.1

---

cultcargo/casa/flag.yml
cultcargo/casa/setjy.yml
cultcargo/casa/split.yml
cultcargo/genesis/casa/casa-inputs.yml
cultcargo/images/python-base/Dockerfile
pyproject.toml

Also adds the flagversions dir as an (implicit) input to flagman.

fixes #113. Fixes #114

---

cultcargo/breizorro.yml
cultcargo/builder/cargo-manifest.yml
cultcargo/genesis/breizorro/breizorro.yaml

new upstream release

---

cultcargo/casa/bandpass.yml
cultcargo/casa/calibration.yml
cultcargo/casa/flag.yml
cultcargo/casa/mstransform.yml
cultcargo/casa/plotms.yml
cultcargo/casa/setjy.yml

I've been fixing caltables and quite a few casa parameters. Unfortunately my branch has diverged from master a little while travelling. So creating this pull request, and will try and merge.
Generally. I have created outputs for caltables. Also added several required parameters to my branch (like some in setjy) that were missing.

Fix caltables

---

cultcargo/casa/calibration.yml
cultcargo/casa/flag.yml

Does what it says on the label.

Add implicit flagversion inputs to flagdata and applycal.

---

bundle-manifest.md
cultcargo/images/python-astro/Dockerfile

One last pre-release fix -- this clears up Lloyd's lightcurve problem.

fixed permissions on astropy cache inside image

---

cultcargo/bdsf.yml
cultcargo/casa/mstransform.yml

Add the combinespws option to mstransform.

Add combinespws

---

.github/workflows/python-package.yml
cultcargo/shadems.yml
pyproject.toml

Add a directory (dir) option to shadems

---

pyproject.toml

@landmanbester please approve, this is with your PFB PR in.

version bump for release

---

cultcargo/builder/cargo-manifest.yml
cultcargo/genesis/pfb-imaging/latest/cgopts.yml
cultcargo/genesis/pfb-imaging/latest/degrid.yaml
cultcargo/genesis/pfb-imaging/latest/dist.yml
cultcargo/genesis/pfb-imaging/latest/fluxtractor.yaml
cultcargo/genesis/pfb-imaging/latest/grid.yaml
cultcargo/genesis/pfb-imaging/latest/gridding.yml
cultcargo/genesis/pfb-imaging/latest/hci.yaml
cultcargo/genesis/pfb-imaging/latest/init.yaml
cultcargo/genesis/pfb-imaging/latest/kclean.yaml
cultcargo/genesis/pfb-imaging/latest/model2comps.yaml
cultcargo/genesis/pfb-imaging/latest/out.yml
cultcargo/genesis/pfb-imaging/latest/pdopts.yml
cultcargo/genesis/pfb-imaging/latest/pmopts.yml
cultcargo/genesis/pfb-imaging/latest/restore.yaml
cultcargo/genesis/pfb-imaging/latest/sara.yaml
cultcargo/genesis/pfb-imaging/latest/smoovie.yaml
cultcargo/genesis/pfb-imaging/latest/spotless.yaml
cultcargo/genesis/pfb-imaging/latest/uncabbedcabs.yml
cultcargo/genesis/pfb-imaging/sync_config.py
pyproject.toml

Adds image for pfb-imaging v0.0.7
